---
title: "Exploracion plantas extintas"
author: "Elgato Saurio"
date: "5/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning =  FALSE, message= FALSE)
library(tidyverse)
library(kableExtra)
library("dplyr")
library(knitr)
```

## Introduccion

### De donde vienen los datos

Estos datos sobre plantas extintas son datos del **PC** y se obtuvieron [del siguiente link](https://github.com/rfordatascience/tidytuesday)

```{r,echo= FALSE, message= FALSE}
plants <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/plants.csv")

actions <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/actions.csv")

threats <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/threats.csv")

```
## Datos de Sudamerica


El numero de especies que hay en sudamerica es de `r plants %>% dplyr::filter(continent == "South America") %>% nrow()` especies.

```{r}
data("msleep")

Tabla <- msleep %>% 
  group_by(vore) %>% 
  summarise_at("sleep_total",.funs = list(Mean = mean, SD = sd)) %>% 
  dplyr::filter(!is.na(vore)) %>% 
  arrange(desc(Mean))

kable(Tabla, digits = 2) %>%  kable_styling(bootstrap_options = c("striped", "hover","condensed"), full_width = FALSE)

```

